package handler

import (
	"context"
	"errors"
	"strconv"
	"time"

	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"gorm.io/gorm"

	apsPb "github.com/ninghonggang/mom-platform/gen/aps"
	commonPb "github.com/ninghonggang/mom-platform/gen/common"
	"mom-platform/services/aps-service/internal/model"
	"mom-platform/services/aps-service/internal/repository"
	"mom-platform/services/aps-service/internal/service"
)

// APSHandler implements all APS gRPC service interfaces.
type APSHandler struct {
	apsPb.UnimplementedMPSServiceServer
	apsPb.UnimplementedMRPServiceServer
	apsPb.UnimplementedScheduleServiceServer
	apsPb.UnimplementedWorkCenterServiceServer
	logger  *zap.Logger
	service *service.APSService
}

// New creates a new APSHandler (alias for NewAPSHandler).
func New(svc *service.APSService, log *zap.Logger) *APSHandler {
	return &APSHandler{logger: log, service: svc}
}

// NewAPSHandler creates a new APSHandler.
func NewAPSHandler(logger *zap.Logger, svc *service.APSService) *APSHandler {
	return &APSHandler{logger: logger, service: svc}
}

// defaultTenantID is used when no tenant is supplied via gRPC metadata.
const defaultTenantID = "0"

// tenantFromCtx extracts the tenant id from the `x-tenant-id` gRPC metadata
// header, falling back to the single-tenant development default.
func tenantFromCtx(ctx context.Context) string {
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		if vals := md.Get("x-tenant-id"); len(vals) > 0 && vals[0] != "" {
			return vals[0]
		}
	}
	return defaultTenantID
}

// Register registers all 4 APS gRPC services on the given gRPC server.
func (h *APSHandler) Register(srv *grpc.Server) {
	apsPb.RegisterMPSServiceServer(srv, h)
	apsPb.RegisterMRPServiceServer(srv, h)
	apsPb.RegisterScheduleServiceServer(srv, h)
	apsPb.RegisterWorkCenterServiceServer(srv, h)
}

// ============ MPS Service ============

// CreateMPS persists a new master production schedule in DRAFT status.
// The plan number is auto-generated by the service layer.
func (h *APSHandler) CreateMPS(ctx context.Context, req *apsPb.CreateMPSRequest) (*apsPb.CreateMPSResponse, error) {
	h.logger.Info("CreateMPS",
		zap.String("mps_no", req.GetMpsNo()),
		zap.Int64("material_id", req.GetMaterialId()))

	if req.GetMaterialId() == 0 {
		return nil, status.Error(codes.InvalidArgument, "material_id is required")
	}
	if req.GetQuantity() <= 0 {
		return nil, status.Error(codes.InvalidArgument, "quantity must be positive")
	}

	planMonth := req.GetPlanMonth()
	if planMonth == "" {
		planMonth = time.Now().Format("2006-01")
	}

	plan := &model.MpsPlan{
		TenantID:   tenantFromCtx(ctx),
		PlanMonth:  planMonth,
		MaterialID: uint64(req.GetMaterialId()),
		PlannedQty: req.GetQuantity(),
		Status:     "DRAFT",
	}
	if err := h.service.CreateMpsPlan(ctx, plan); err != nil {
		if errors.Is(err, service.ErrDuplicateCode) {
			return nil, status.Errorf(codes.AlreadyExists, "create MPS: %v", err)
		}
		h.logger.Error("create MPS failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "create MPS: %v", err)
	}
	return &apsPb.CreateMPSResponse{Mps: modelToProtoMps(plan)}, nil
}

func (h *APSHandler) GetMPS(ctx context.Context, req *apsPb.GetMPSRequest) (*apsPb.GetMPSResponse, error) {
	h.logger.Info("GetMPS", zap.Int64("id", req.GetId()))

	p, err := h.service.GetMpsPlan(ctx, uint64(req.GetId()))
	if err != nil {
		if err == gorm.ErrRecordNotFound || err == repository.ErrNotFound {
			return nil, status.Errorf(codes.NotFound, "MPS %d not found", req.GetId())
		}
		h.logger.Error("get MPS failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "get MPS: %v", err)
	}
	return &apsPb.GetMPSResponse{Mps: modelToProtoMps(p)}, nil
}

func (h *APSHandler) ListMPS(ctx context.Context, req *apsPb.ListMPSRequest) (*apsPb.ListMPSResponse, error) {
	h.logger.Info("ListMPS")

	offset, limit := paginationToOffsetLimit(req.GetPagination())
	tenantID := strconv.FormatInt(req.GetTenantId(), 10)

	items, total, err := h.service.ListMpsPlans(ctx, tenantID, offset, limit)
	if err != nil {
		h.logger.Error("list MPS failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "list MPS: %v", err)
	}

	resp := &apsPb.ListMPSResponse{
		Items:      make([]*apsPb.MasterProductionSchedule, 0, len(items)),
		Pagination: buildPagination(req.GetPagination(), total),
	}
	for i := range items {
		resp.Items = append(resp.Items, modelToProtoMps(&items[i]))
	}
	return resp, nil
}

func (h *APSHandler) ReleaseMPS(ctx context.Context, req *apsPb.ReleaseMPSRequest) (*apsPb.ReleaseMPSResponse, error) {
	h.logger.Info("ReleaseMPS", zap.Int64("id", req.GetId()), zap.String("operator", req.GetOperator()))

	p, err := h.service.ReleaseMPS(ctx, uint64(req.GetId()))
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, status.Errorf(codes.NotFound, "MPS %d not found", req.GetId())
		}
		if err == service.ErrInvalidStatus {
			return nil, status.Errorf(codes.FailedPrecondition, "cannot release MPS: %v", err)
		}
		h.logger.Error("release MPS failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "release MPS: %v", err)
	}
	return &apsPb.ReleaseMPSResponse{Mps: modelToProtoMps(p)}, nil
}

// ============ MRP Service ============

func (h *APSHandler) RunMRP(ctx context.Context, req *apsPb.RunMRPRequest) (*apsPb.RunMRPResponse, error) {
	h.logger.Info("RunMRP", zap.Int64("mps_id", req.GetMpsId()), zap.String("operator", req.GetOperator()))

	mps, err := h.service.GetMpsPlan(ctx, uint64(req.GetMpsId()))
	if err != nil {
		return nil, status.Errorf(codes.NotFound, "MPS %d not found", req.GetMpsId())
	}

	plans, err := h.service.RunMrp(ctx, mps.TenantID, mps.ID)
	if err != nil {
		h.logger.Error("run MRP failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "run MRP: %v", err)
	}

	base := modelToProtoBaseModel(mps.ID, mps.TenantID)
	mrp := &apsPb.MaterialRequirementsPlan{
		Base:     base,
		MrpNo:    mps.PlanNo + "-MRP",
		MpsId:    int64(mps.ID),
		MpsNo:    mps.PlanNo,
		MrpType:  "MRP",
		PlanDate: timestamppb.Now(),
		Status:   commonPb.MrpStatus_MRP_STATUS_COMPLETED,
		Items:    make([]*apsPb.MRPItem, 0, len(plans)),
	}
	for i := range plans {
		item := &apsPb.MRPItem{
			Base:             modelToProtoBaseModel(plans[i].ID, plans[i].TenantID),
			MrpId:            int64(plans[i].MpsID),
			MaterialId:       int64(plans[i].MaterialID),
			GrossRequirement: plans[i].GrossReq,
			NetRequirement:   plans[i].NetReq,
		}
		mrp.Items = append(mrp.Items, item)
	}

	return &apsPb.RunMRPResponse{Mrp: mrp}, nil
}

func (h *APSHandler) GetMRP(ctx context.Context, req *apsPb.GetMRPRequest) (*apsPb.GetMRPResponse, error) {
	h.logger.Info("GetMRP", zap.Int64("id", req.GetId()))

	plans, err := h.service.GetMrpPlansByMpsID(ctx, uint64(req.GetId()))
	if err != nil {
		h.logger.Error("get MRP plans failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "get MRP: %v", err)
	}

	mrp := &apsPb.MaterialRequirementsPlan{
		Base:     modelToProtoBaseModel(uint64(req.GetId()), strconv.FormatInt(req.GetId(), 10)),
		MpsId:    req.GetId(),
		Status:   commonPb.MrpStatus_MRP_STATUS_COMPLETED,
		Items:    make([]*apsPb.MRPItem, 0, len(plans)),
	}
	for i := range plans {
		item := &apsPb.MRPItem{
			Base:             modelToProtoBaseModel(plans[i].ID, plans[i].TenantID),
			MrpId:            int64(plans[i].MpsID),
			MaterialId:       int64(plans[i].MaterialID),
			GrossRequirement: plans[i].GrossReq,
			NetRequirement:   plans[i].NetReq,
		}
		mrp.Items = append(mrp.Items, item)
	}

	return &apsPb.GetMRPResponse{Mrp: mrp}, nil
}

// ============ Schedule Service ============

func (h *APSHandler) CreateSchedule(ctx context.Context, req *apsPb.CreateScheduleRequest) (*apsPb.CreateScheduleResponse, error) {
	h.logger.Info("CreateSchedule")

	if req.GetPlan() == nil {
		return nil, status.Error(codes.InvalidArgument, "schedule plan is required")
	}

	plan := req.GetPlan()
	tenantID := strconv.FormatInt(plan.GetBase().GetTenantId(), 10)

	job := &model.ScheduleJob{
		TenantID:     tenantID,
		JobNo:        plan.GetPlanNo(),
		MpsID:        uint64(plan.GetMpsId()),
		PlanType:     planTypeToModel(plan.GetPlanType()),
		Algorithm:    algorithmToModel(plan.GetAlgorithm()),
		WorkCenterID: uint64(plan.GetWorkcenterId()),
		Status:       "PENDING",
	}
	if ts := plan.GetStartDate(); ts != nil && ts.IsValid() {
		job.PlannedStart = ts.AsTime()
	}
	if ts := plan.GetEndDate(); ts != nil && ts.IsValid() {
		job.PlannedEnd = ts.AsTime()
	}

	created, err := h.service.CreateScheduleJob(ctx, job)
	if err != nil {
		if err == service.ErrWorkCenterNotFound {
			return nil, status.Errorf(codes.NotFound, "work center %d not found", plan.GetWorkcenterId())
		}
		h.logger.Error("create schedule failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "create schedule: %v", err)
	}

	result := modelToProtoSchedulePlan(created)
	return &apsPb.CreateScheduleResponse{Plan: result}, nil
}

func (h *APSHandler) GetSchedule(ctx context.Context, req *apsPb.GetScheduleRequest) (*apsPb.GetScheduleResponse, error) {
	h.logger.Info("GetSchedule", zap.Int64("id", req.GetId()))

	job, err := h.service.GetScheduleJob(ctx, uint64(req.GetId()))
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, status.Errorf(codes.NotFound, "schedule %d not found", req.GetId())
		}
		h.logger.Error("get schedule failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "get schedule: %v", err)
	}

	return &apsPb.GetScheduleResponse{Plan: modelToProtoSchedulePlan(job)}, nil
}

func (h *APSHandler) ListSchedules(ctx context.Context, req *apsPb.ListSchedulesRequest) (*apsPb.ListSchedulesResponse, error) {
	h.logger.Info("ListSchedules")

	offset, limit := paginationToOffsetLimit(req.GetPagination())
	tenantID := strconv.FormatInt(req.GetTenantId(), 10)

	items, total, err := h.service.ListScheduleJobs(ctx, tenantID, offset, limit)
	if err != nil {
		h.logger.Error("list schedules failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "list schedules: %v", err)
	}

	resp := &apsPb.ListSchedulesResponse{
		Items:      make([]*apsPb.SchedulePlan, 0, len(items)),
		Pagination: buildPagination(req.GetPagination(), total),
	}
	for i := range items {
		resp.Items = append(resp.Items, modelToProtoSchedulePlan(&items[i]))
	}
	return resp, nil
}

func (h *APSHandler) PublishSchedule(ctx context.Context, req *apsPb.PublishScheduleRequest) (*apsPb.PublishScheduleResponse, error) {
	h.logger.Info("PublishSchedule", zap.Int64("plan_id", req.GetPlanId()), zap.String("operator", req.GetOperator()))

	job, err := h.service.PublishScheduleJob(ctx, uint64(req.GetPlanId()))
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, status.Errorf(codes.NotFound, "schedule %d not found", req.GetPlanId())
		}
		if err == service.ErrInvalidStatus {
			return nil, status.Errorf(codes.FailedPrecondition, "cannot publish schedule: %v", err)
		}
		h.logger.Error("publish schedule failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "publish schedule: %v", err)
	}

	return &apsPb.PublishScheduleResponse{Plan: modelToProtoSchedulePlan(job)}, nil
}

// ============ WorkCenter Service ============

func (h *APSHandler) ListWorkCenters(ctx context.Context, req *apsPb.ListWorkCentersRequest) (*apsPb.ListWorkCentersResponse, error) {
	h.logger.Info("ListWorkCenters")

	tenantID := strconv.FormatInt(req.GetTenantId(), 10)
	var items []model.WorkCenter
	var err error

	if req.GetWorkshopId() > 0 {
		items, err = h.service.ListWorkCentersByWorkshop(ctx, tenantID, uint64(req.GetWorkshopId()))
	} else {
		items, _, err = h.service.ListWorkCenters(ctx, tenantID, 0, 100)
	}
	if err != nil {
		h.logger.Error("list work centers failed", zap.Error(err))
		return nil, status.Errorf(codes.Internal, "list work centers: %v", err)
	}

	resp := &apsPb.ListWorkCentersResponse{
		Items: make([]*apsPb.WorkCenter, 0, len(items)),
	}
	for i := range items {
		resp.Items = append(resp.Items, modelToProtoWorkCenter(&items[i]))
	}
	return resp, nil
}

// ============ Conversion Helpers ============

func paginationToOffsetLimit(p *commonPb.Pagination) (int, int) {
	page, pageSize := int32(1), int32(20)
	if p != nil {
		if p.GetPage() > 0 {
			page = p.GetPage()
		}
		if p.GetPageSize() > 0 {
			pageSize = p.GetPageSize()
		}
	}
	return int((page - 1) * pageSize), int(pageSize)
}

func buildPagination(p *commonPb.Pagination, total int64) *commonPb.Pagination {
	page := int32(1)
	pageSize := int32(20)
	if p != nil {
		if p.GetPage() > 0 {
			page = p.GetPage()
		}
		if p.GetPageSize() > 0 {
			pageSize = p.GetPageSize()
		}
	}
	totalPages := int32(0)
	if pageSize > 0 {
		totalPages = int32((total + int64(pageSize) - 1) / int64(pageSize))
	}
	return &commonPb.Pagination{
		Page:       page,
		PageSize:   pageSize,
		Total:      int32(total),
		TotalPages: totalPages,
	}
}

func modelToProtoBaseModel(id uint64, tenantID string) *commonPb.BaseModel {
	tid, _ := strconv.ParseInt(tenantID, 10, 64)
	return &commonPb.BaseModel{
		Id:       int64(id),
		TenantId: tid,
	}
}

func modelToProtoMps(p *model.MpsPlan) *apsPb.MasterProductionSchedule {
	base := modelToProtoBaseModel(p.ID, p.TenantID)
	return &apsPb.MasterProductionSchedule{
		Base:       base,
		MpsNo:      p.PlanNo,
		PlanMonth:  p.PlanMonth,
		MaterialId: int64(p.MaterialID),
		Quantity:   p.PlannedQty,
		Status:     modelToProtoMpsStatus(p.Status),
	}
}

func modelToProtoMpsStatus(s string) commonPb.MpsStatus {
	switch s {
	case "DRAFT":
		return commonPb.MpsStatus_MPS_STATUS_DRAFT
	case "CONFIRMED":
		return commonPb.MpsStatus_MPS_STATUS_IN_PROGRESS
	case "RELEASED":
		return commonPb.MpsStatus_MPS_STATUS_RELEASED
	case "CLOSED":
		return commonPb.MpsStatus_MPS_STATUS_COMPLETED
	default:
		return commonPb.MpsStatus_MPS_STATUS_UNSPECIFIED
	}
}

func modelToProtoWorkCenter(wc *model.WorkCenter) *apsPb.WorkCenter {
	base := modelToProtoBaseModel(wc.ID, wc.TenantID)
	return &apsPb.WorkCenter{
		Base:             base,
		WorkCenterCode:   wc.CenterCode,
		WorkCenterName:   wc.CenterName,
		WorkshopId:       int64(wc.WorkshopID),
		StandardCapacity: wc.CapacityPerDay,
		EfficiencyFactor: wc.Efficiency,
		Status:           modelToProtoWorkCenterStatus(wc.Status),
	}
}

func modelToProtoWorkCenterStatus(s string) commonPb.WorkCenterStatus {
	switch s {
	case "ACTIVE":
		return commonPb.WorkCenterStatus_WORK_CENTER_STATUS_ACTIVE
	case "INACTIVE":
		return commonPb.WorkCenterStatus_WORK_CENTER_STATUS_INACTIVE
	default:
		return commonPb.WorkCenterStatus_WORK_CENTER_STATUS_UNSPECIFIED
	}
}

func modelToProtoSchedulePlan(job *model.ScheduleJob) *apsPb.SchedulePlan {
	base := modelToProtoBaseModel(job.ID, job.TenantID)

	plan := &apsPb.SchedulePlan{
		Base:         base,
		PlanNo:       job.JobNo,
		MpsId:        int64(job.MpsID),
		PlanType:     planTypeFromModel(job.PlanType),
		Algorithm:    algorithmFromModel(job.Algorithm),
		WorkcenterId: int64(job.WorkCenterID),
		Status:       schedulePlanStatusFromModel(job.Status),
	}
	// 零值时间不回填，避免前端收到 year 1 的 -62135596800。
	if !job.PlannedStart.IsZero() {
		plan.StartDate = timestamppb.New(job.PlannedStart)
	}
	if !job.PlannedEnd.IsZero() {
		plan.EndDate = timestamppb.New(job.PlannedEnd)
	}
	return plan
}

// planTypeToModel / planTypeFromModel — proto 枚举与 model 字符串互转。
func planTypeToModel(t commonPb.PlanType) string {
	switch t {
	case commonPb.PlanType_PLAN_TYPE_ROUGH:
		return "ROUGH"
	case commonPb.PlanType_PLAN_TYPE_FINE:
		return "FINE"
	default:
		return ""
	}
}

func planTypeFromModel(s string) commonPb.PlanType {
	switch s {
	case "ROUGH":
		return commonPb.PlanType_PLAN_TYPE_ROUGH
	case "FINE":
		return commonPb.PlanType_PLAN_TYPE_FINE
	default:
		return commonPb.PlanType_PLAN_TYPE_UNSPECIFIED
	}
}

func algorithmToModel(a commonPb.SchedulingAlgorithm) string {
	switch a {
	case commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_FIFO:
		return "FIFO"
	case commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_EDD:
		return "EDD"
	case commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_SPT:
		return "SPT"
	case commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_LPT:
		return "LPT"
	default:
		return ""
	}
}

func algorithmFromModel(s string) commonPb.SchedulingAlgorithm {
	switch s {
	case "FIFO":
		return commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_FIFO
	case "EDD":
		return commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_EDD
	case "SPT":
		return commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_SPT
	case "LPT":
		return commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_LPT
	default:
		return commonPb.SchedulingAlgorithm_SCHEDULING_ALGORITHM_UNSPECIFIED
	}
}

func schedulePlanStatusFromModel(s string) commonPb.SchedulePlanStatus {
	switch s {
	case "PENDING":
		return commonPb.SchedulePlanStatus_SCHEDULE_PLAN_STATUS_PENDING
	case "SCHEDULED":
		return commonPb.SchedulePlanStatus_SCHEDULE_PLAN_STATUS_RUNNING
	case "RUNNING":
		return commonPb.SchedulePlanStatus_SCHEDULE_PLAN_STATUS_RUNNING
	case "COMPLETED":
		return commonPb.SchedulePlanStatus_SCHEDULE_PLAN_STATUS_COMPLETED
	default:
		return commonPb.SchedulePlanStatus_SCHEDULE_PLAN_STATUS_PENDING
	}
}
