server:
  port: 50054
  name: eam-service
database:
  host: localhost
  port: 5432
  user: mom
  password: mom123
  dbname: mom_eam
  sslmode: disable
nats:
  url: nats://localhost:4222
redis:
  addr: localhost:6379
